### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by enzohnnn** [lpechayco/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
  - Your code examples are either just text or images. It is good to make use of markdown's backticks for code examples!
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Well done! Just a few easy fixes and your report is perfect.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by lpechayco** [comment]
Hi! so I had some code examples that showed output, which I think is a lot to type out in backticks, so I only re-did the code examples in backticks that were user input into the terminal. Is that okay?

**Comment by enzohnnn** [comment]
Hi, you fixed the issue with the report being on its own page. It still seems like the code examples still don't have the proper backticks. You have a ton of terminal commands in your report but we were looking to make use of markdown's three backticks for code (```). There is a slight difference in using the singular backtick versus the three backticks in markdown but it makes a noticeable difference for the readability of the lab report. Some students even rewrote the WhereAmI class putting the code in the triple backticks and it looks nice and easy to copy if need be.

**Comment by lpechayco** [comment]
Ah okay I see, I will fix it, thank you!

**Comment by lpechayco** [comment]
Hello, I fixed the backticks and submitted a regrade request last week, just wanted to make sure you saw it. Thank you!
